### ISSUE TITLE
Trying to train on chunks longer than 10s

### ISSUE THREAD

**Issue by Saltb0xApps** [ldzhangyx/instruct-MusicGen#5]
Hey! I've been able to use this to train on my custom data, but it seems like i run out of memory on an 80GB A100 GPU if i pass time_in_seconds > 10. The default value is 5 seconds, and i'm able to scale it up to 10, but not past that. 

Any ideas on how to go about training on larger chunks closer to 30s?

error -
```
 [?25h[2024-06-24 07:34:42,607][src.utils.utils][ERROR] - [rank: 0]
28 Traceback (most recent call last):
29   File "/home/akhil/instruct-MusicGen/src/utils/utils.py", line 68, in wrap
30     metric_dict, object_dict = task_func(cfg=cfg)
31   File "/home/akhil/instruct-MusicGen/src/train.py", line 92, in train
32     trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
33   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
34     call._call_and_handle_interrupt(
35   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
36     return trainer_fn(*args, **kwargs)
37   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
38     self._run(model, ckpt_path=ckpt_path)
39   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
40     results = self._run_stage()
41   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1028, in _run_stage
42     self._run_sanity_check()
43   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1057, in _run_sanity_check
44     val_loop.run()
45   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
46     return loop_run(self, *args, **kwargs)
47   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 135, in run
48     self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
49   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 396, in _evaluation_step
50     output = call._call_strategy_hook(trainer, hook_name, *step_args)
51   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 311, in _call_strategy_hook
52     output = fn(*args, **kwargs)
53   File "/home/akhil/.local/lib/python3.9/site-packages/lightning/pytorch/strategies/strategy.py", line 411, in validation_step
54     return self.lightning_module.validation_step(*args, **kwargs)
55   File "/home/akhil/instruct-MusicGen/src/models/instructmusicgenadapter_module.py", line 157, in validation_step
56     loss, preds, targets = self.model_step(batch)
57   File "/home/akhil/instruct-MusicGen/src/models/instructmusicgenadapter_module.py", line 120, in model_step
58     loss, preds, y = self.forward(batch)
59   File "/home/akhil/instruct-MusicGen/src/models/instructmusicgenadapter_module.py", line 79, in forward
60     output = self.model(
61   File "/home/akhil/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
62     return self._call_impl(*args, **kwargs)
63   File "/home/akhil/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
64     return forward_call(*args, **kwargs)
65   File "/home/akhil/instruct-MusicGen/src/models/components/model.py", line 388, in forward
66     embed_fn = self.cp_transformer.forward(condition_audio_code=condition_audio_code,
67   File "/home/akhil/instruct-MusicGen/src/models/components/model.py", line 313, in forward
68     embedding = self.merge_linear[i](encoded_condition) + self.pos_emb[i + 1][None, :T].repeat(B, 1, 1)
69 RuntimeError: The size of tensor a (1501) must match the size of tensor b (501) at non-singleton dimension 1
```

**Comment by ldzhangyx** [comment]
I designed the positional embedding with the size of 501. You can change the size to a larger one to train longer query.

**Comment by ldzhangyx** [comment]
It should be `self.pos_emb`.

**Comment by Saltb0xApps** [comment]
that worked, thank you - the only thing is that inputs & ground_truth are 30s, but the outputs are still restricted to 10s. I think there is something happening in the `model.py` -> `generate` function that is causing audio to be clipped still?

**Comment by Saltb0xApps** [comment]
nvm had to update duration a few other places and that fixed it!
